symbol = {
	'Aarambha Chautari Laghubitta Bittiya Sanstha Limited': 'ACLBSL',
	'Agricultural Development Bank Limited': 'ADBL',
	'4% Agricultural Bond': 'ADBLB',
	'Agricultural Bond (8 Year)': 'ADBLB86',
	'Agricultural Bond (9 Year)': 'ADBLB87',
	'10.35% Agricultural Bank Debenture 2083': 'ADBLD83',
	'Arun Valley Hydropower Development Co. Ltd.': 'AHPC',
	'Ajod Insurance Limited': 'AIL',
	'ADHIKHOLA LAGHUBITTA BITTIYA SANSTHA LIMITED': 'AKBSL',
	'Ankhu Khola Jalvidhyut Company Ltd': 'AKJCL',
	'Arun Kabeli Power Ltd.': 'AKPL',
	'Asha Laghubitta Bittiya Sanstha Ltd': 'ALBSL',
	'Asian Life Insurance Co. Limited': 'ALICL',
	'Arambha Microfinance Bittiya Sanstha Ltd.': 'AMFI',
	'Api Power Company Ltd.': 'API',
	'Arun Vanaspati Udhyog Limited': 'AVU',
	'Barun Hydropower Co. Ltd.': 'BARUN',
	'Balephi Hydropower Limited': 'BHL',
	'Buddha Bhumi Nepal Hydropower Company Limited': 'BNHC',
	'Bottlers Nepal (Balaju) Limited': 'BNL',
	'Bottlers Nepal (Terai) Limited': 'BNT',
	'8% BOK Debenture 2079': 'BOKD2079',
	'8.5% BOK Debenture 2086': 'BOKD86',
	'Bank of Kathmandu Ltd.': 'BOKL',
	'Butwal Power Company Limited': 'BPCL',
	'Birat Shoe Limited': 'BSL',
	'Butwal Spinning Mills Limited': 'BSM',
	'Chhimek Laghubitta Bittiya Sanstha Limited': 'CBBL',
	'Civil Bank Ltd': 'CBL',
	'Civil Bank Debenture 2088': 'CBLD88',
	'Century Debenture 2088': 'CCBD88',
	'Century Commercial Bank Ltd.': 'CCBL',
	'City Express Finance Co. Limited': 'CEFL',
	'Central Finance Co. Ltd.': 'CFCL',
	'CEDB Hydropower Development Company Limited': 'CHDC',
	'Chhyangdi Hydropower Ltd.': 'CHL',
	'Citizen Investment Trust': 'CIT',
	'10.25% Citizens Bank Debenture 2086': 'CIZBD86',
	'Civil Laghubitta Bittiya Sanstha Ltd.': 'CLBSL',
	'Capital Merchant Bank & Finance Co. Ltd.': 'CMB',
	'Citizens Mutual Fund -1': 'CMF1',
	'CITIZENS MUTUAL FUND 2': 'CMF2',
	'Corporate Development Bank Limited': 'CORBL',
	'CYC Nepal Laghubitta Bittiya Sanstha Limited': 'CYCL',
	'Citizens Bank International Limited': 'CZBIL',
	'Deprosc Laghubitta Bittiya Sanstha Limited': 'DDBL',
	'Dibyashwori Hydropower Ltd.': 'DHPL',
	'Dordi Khola Jal Bidyut Company Limited': 'DORDI',
	'Everest Bank Limited': 'EBL',
	'Everest Bank Limited Con. Pref.': 'EBLCP',
	'Excel Development Bank Ltd.': 'EDBL',
	'First Micro Finance Laghubitta Bittiya Sanstha Limited': 'FMDBL',
	'Forward Microfinance Laghubitta Bittiya Sanstha Limited': 'FOWAD',
	'Garima Debenture, 2085': 'GBBD85',
	'Garima Bikas Bank Limited': 'GBBL',
	'10.25% GLOBAL IME BANK LTD. DEBENTURE 2080/81': 'GBD80/81',
	'Global IME Bank Limited Debenture 2086/87': 'GBILD86/87',
	'Global IME Bank Limited': 'GBIME',
	'Grameen Bikas Laghubitta Bittiya Sanstha Ltd.': 'GBLBS',
	'Gandaki Bikas Bank Limited': 'GDBL',
	'Goodwill Finance Limited': 'GFCL',
	'Ghodighoda Laghubitta Bittiya Sanstha Ltd.': 'GGBSL',
	'Ghalemdi Hydro Limited': 'GHL',
	'General Insurance Company Nepal Ltd': 'GIC',
	'Global IME Laghubitta Bittiya Sanstha Ltd.': 'GILB',
	'Global IME Samunnat Scheme-1': 'GIMES1',
	'Gurans Laghubitta Bittiya Sanstha Limited': 'GLBSL',
	'GreenLife Hydropower Limited': 'GLH',
	'Green Development Bank Ltd.': 'GRDBL',
	'Gorakhkali Rubber Udhyog Limited': 'GRU',
	'Gurkhas Finance Ltd.': 'GUFL',
	'Green Ventures Limited': 'GVL',
	'12% Goodwill Finance Limited Debenture 2083': 'GWFD83',
	'Hamro Bikas Bank Ltd.': 'HAMRO',
	'Hathway Finance Company Limited': 'HATH',
	'Himalayan Bank Limited': 'HBL',
	'10% Himalayan Bank Debenture 2083': 'HBLD83',
	'Harisiddhi Brick And Tiles Limited': 'HBT',
	'Himal Dolakha Hydropower Company Limited': 'HDHPC',
	'Himalayan Distillery Limited': 'HDL',
	'Himalayan Finance Limited (Bittiya Sanstha)': 'HFL',
	'Himalayan General Insurance Co. Ltd': 'HGI',
	'Hydorelectricity Investment and Development Company Ltd': 'HIDCL',
	'Himalayan Power Partner Ltd.': 'HPPL',
	'Himalaya Urja Bikas Company Limited': 'HURJA',
	'Infinity Laghubitta Bittiya Sanstha Limited': 'ILBS',
	'Jalpa Samudayik Laghubitta Bittiya Sanstha Limited': 'JALPA',
	'Jyoti Bikash Bank Bond 2087': 'JBBD87',
	'Jyoti Bikas Bank Limited': 'JBBL',
	'Jeevan Bikas Laghubitta  Bittya Sanstha Ltd': 'JBLB',
	'Janata Bank Nepal Ltd.': 'JBNL',
	'Janaki Finance Company Limited': 'JFL',
	'Jyoti Life Insurance Company Limited': 'JLI',
	'Joshi Hydropower Development Company Ltd': 'JOSHI',
	'Janautthan Samudayic Laghubitta Bittya Sanstha Limited': 'JSLBB',
	'Jyoti Sinning Mills Limited': 'JSM',
	'Kumari Bank Limited': 'KBL',
	'10.25% KBL Debenture 2086': 'KBLD86',
	'Kumari Equity Fund': 'KEF',
	'Khanikhola Hydropower Co. Ltd.': 'KKHC',
	'Kisan Lagubitta Bittiya Sanstha Limited': 'KLBSL',
	'Kalika Laghubitta Bittiya Sanstha Ltd': 'KMCDB',
	'Kamana Sewa Bikas Bank Limited': 'KSBBL',
	'9% Kamana Sewa Bikas Bank Limited Debenture 2087': 'KSBBLD87',
	'Lumbini Bikas Bank Ltd.': 'LBBL',
	'Laxmi Bank Limited': 'LBL',
	'10% Laxmi Bank Debenture 2086': 'LBLD86',
	'8.5% Laxmi Bank Debenture 2088': 'LBLD88',
	'Liberty Energy Company Limited': 'LEC',
	'Laxmi Equity Fund': 'LEMF',
	'Lalitpur Finance Ltd.': 'LFC',
	'Lumbini General Insurance Co. Ltd.': 'LGIL',
	'Life Insurance Corporation (Nepal) Limited': 'LICN',
	'Laxmi Laghubitta Bittiya Sanstha Ltd.': 'LLBS',
	'Laxmi Unnati Kosh': 'LUK',
	'Madhya Bhotekoshi Jalavidyut Company Limited': 'MBJC',
	'Machhapuchhre Bank Limited': 'MBL',
	'10.25% Machhapuchhre Bank Debenture 2085': 'MBLD2085',
	'8.5% Machhapuchchhre Debenture 2087': 'MBLD87',
	'Mero Microfinance Bittiya Sanstha Ltd.': 'MERO',
	'Manjushree Finance Ltd.': 'MFIL',
	'9.5% Manjushree Finance Limited Debenture 2085': 'MFLD85',
	'Mountain Hydro Nepal Limited': 'MHNL',
	'Mailung Khola Jal Vidhyut Company Limited': 'MKJC',
	'Manakamana Smart Laghubitta Bittiya Sanstha Limited': 'MKLB',
	'Mithila LaghuBitta Bittiya Sanstha Limited': 'MLBBL',
	'Mahalaxmi Bikas Bank Ltd.': 'MLBL',
	'Manushi Laghubitta Bittiya Sanstha Limited': 'MLBS',
	'Mahila Lagubitta Bittiya Sanstha Limited': 'MLBSL',
	'Mega Mutual Fund -1': 'MMF1',
	'Mirmire Microfinance Development Bank Ltd.': 'MMFDB',
	'Muktinath Bikas Bank Ltd.': 'MNBBL',
	'Muktinath Debenture 2084/85': 'MND84/85',
	'Multipurpose Finance Company  Limited': 'MPFL',
	'Mahuli Laghubitta Bittiya Sanstha Limited': 'MSLB',
	'Mahila Sahayatra Microfinance Bittiya Sanstha Ltd.': 'MSMBS',
	'Nepal Agro Laghubitta Bittiya Sanstha Limited': 'NAGRO',
	'Nepal Bangladesh Bank Limited': 'NBB',
	'10.25% NBBL Debenture 2085': 'NBBD2085',
	'Nepal Bitumin And Barrel Udhyog Limited': 'NBBU',
	'NABIL BALANCED FUND-2': 'NBF2',
	'Nabil Balanced Fund-3': 'NBF3',
	'Nepal Bank Limited': 'NBL',
	'10% Nabil Debenture 2082': 'NBLD82',
	'Nabil Debenture 2085': 'NBLD85',
	'8.5% Nepal Bank Debenture 2087': 'NBLD87',
	'Nepal Credit And Commercial Bank Limited': 'NCCB',
	'9.5% NCC Debenture 2086': 'NCCD86',
	'Nabil Equity Fund': 'NEF',
	'NESDO Sambridha Laghubitta Bittiya Sanstha Limited': 'NESDO',
	'Nepal Film Development Company Limited': 'NFD',
	'Nepal Finance Ltd.': 'NFS',
	'Ngadi Group Power Ltd.': 'NGPL',
	'10.5 % NEPAL INVESTMENT DEBENTURE 2082': 'NIBD2082',
	'8.5% Nepal Investment Bank Debenture 2084': 'NIBD84',
	'NIBL Pragati Fund': 'NIBLPF',
	'NIBL Samriddhi Fund -2': 'NIBSF2',
	'NIC Asia Bank Ltd.': 'NICA',
	'10% NIC Asia Debenture 2085/86': 'NICAD 85/86',
	'9% NIC Asia Debenture 2081/82': 'NICAD8182',
	'11% NIC Asia Debenture 082/83': 'NICAD8283',
	'NIC Asia Balanced Fund': 'NICBF',
	'10.25% NIC Asia Debenture 2083/84': 'NICD83/84',
	'NIC ASIA Rinpatra 2088': 'NICD88',
	'NIC Asia Growth Fund': 'NICGF',
	'Nepal Insurance Co. Ltd.': 'NICL',
	'NIC ASIA Laghubitta Bittiya Sanstha Limited': 'NICLBSL',
	'NIC Asia Select Fund 30': 'NICSF',
	'NIDC Development Bank Ltd.': 'NIDC',
	'Nepal Infrastructure Bank Limited': 'NIFRA',
	'NLG Insurance Company Ltd.': 'NLG',
	'Nepal Life Insurance Co. Ltd.': 'NLIC',
	'National Life Insurance Co. Ltd.': 'NLICL',
	'Nepal Lube Oil Limited': 'NLO',
	'NMB Bank Limited': 'NMB',
	'NMB 50': 'NMB50',
	'10 % NMB DEBENTURE 2085': 'NMBD2085',
	'NMB Debenture 8.50% - 2087/88': 'NMBD87/88',
	'NMB Energy Bond 4% - 2092/93': 'NMBEB92/93',
	'NMB Hybrid Fund L-1': 'NMBHF1',
	'NMB  Microfinance Bittiya Sanstha Ltd.': 'NMBMF',
	'National Microfinance Laghubitta Bittiya Sanstha Limited': 'NMFBS',
	'Nepal Reinsurance Company Limited': 'NRIC',
	'NRN Infrastructure and Development Limited': 'NRN',
	'Naya Sarathi Laghubitta Bittiya Sanstha Limited': 'NSLB',
	'Nepal Share Markets Ltd.': 'NSM',
	'Nepal Doorsanchar Company Limited': 'NTC',
	'Nepal Welfare Company Limited': 'NWC',
	'Nyadi Hydropower Limited': 'NYADI',
	'Om Development Bank Ltd.': 'ODBL',
	'Oriental Hotels Limited': 'OHL',
	'8.75% Prime Debenture 2085': 'PBD85',
	'10% Prabhu Bank Debenture 2084': 'PBLD84',
	'10.25% Prabhu Bank  Debenture 2086': 'PBLD86',
	'8.5% Prabhu Bank Debenture 2087': 'PBLD87',
	'Prime Commercial Bank Ltd.': 'PCBL',
	'Pokhara Finance Ltd.': 'PFL',
	'Premier Insurance Company (Nepal) Limited': 'PIC',
	'Prudential Insurance Co. Ltd.': 'PICL',
	'Prabhu Life Insurance Limited': 'PLI',
	'Prime Life Insurance Company Limited': 'PLIC',
	'Panchakanya Mai Hydropower Ltd': 'PMHPL',
	'Panchthar Power Compant Limited': 'PPCL',
	'Prabhu Insurance Ltd.': 'PRIN',
	'Radhi Bidyut Company Ltd': 'RADHI',
	'8.5% RBBL Debenture 2083': 'RBBD83',
	'Rastriya Beema Company Limited': 'RBCL',
	'River Falls Power Limited': 'RFPL',
	'Ridi Hydropower Development Company Ltd.': 'RHPC',
	'RASUWAGADHI HYDROPOWER COMPANY LIMITED': 'RHPL',
	'Raghupati Jute Mills Limited': 'RJM',
	'Reliance Finance Ltd.': 'RLFL',
	'Reliance Life Insurance Limited': 'RLI',
	'RMDC Laghubitta Bittiya Sanstha Ltd.': 'RMDC',
	'RBB Mutual Fund 1': 'RMF1',
	'Rairang Hydropower Development Company Ltd.': 'RRHP',
	'RSDC Laghubitta Bittiya Sanstha Ltd.': 'RSDC',
	'Rastra Utthan Laghubitta Sanstha Limited': 'RULB',
	'Ru Ru Jalbidhyut Pariyojana Limited': 'RURU',
	'SABAIKO LAGHUBITTA BITTIYA SANSTHA LIMITED': 'SABSL',
	'Shangrila Development Bank Ltd.': 'SADBL',
	'10% Sanima Bank Limited Debenture': 'SAND2085',
	'Sanima Bank Limited': 'SANIMA',
	'Saptakoshi Development Bank Ltd': 'SAPDBL',
	'Sahayogi Bikas Bank Limited': 'SBBLJ',
	'Sunrise Bluechip Fund': 'SBCF',
	'8.5% Sanima Debenture 2087': 'SBD87',
	'Nepal SBI Bank Limited': 'SBI',
	'10% Nepal SBI Bank Debenture 2086': 'SBIBD86',
	'Siddhartha Bank Limited': 'SBL',
	'10.50% SBL Debenture 2082': 'SBLD2082',
	'10.25% SBL Debenture 2083': 'SBLD83',
	'8.5% SBL Debenture 2084': 'SBLD84',
	'Shree Bhrikuti Pulp And Paper Limited': 'SBPP',
	'Standard Chartered Bank Limited': 'SCB',
	'Shangri-la Development Bank Debenture 2087': 'SDBD87',
	'Swadeshi Laghubitta Bittiya Sanstha Ltd.': 'SDESI',
	'Sadhana Laghubitta Bittiya Sanstha Limited': 'SDLBSL',
	'Samriddhi Finance Company Limited': 'SFCL',
	'Shrijana Finance  (Bittaya Sanstha)': 'SFFIL',
	'Sunrise First Mutual Fund': 'SFMF',
	'Sanima General Insurance Limited': 'SGI',
	'Sahara Bikas Bank Ltd.': 'SHBL',
	'Singati Hydro Energy Limited': 'SHEL',
	'Shine Resunga Development Bank Ltd.': 'SHINE',
	'SHIVAM CEMENTS LTD': 'SHIVM',
	'Soaltee Hotel Limited': 'SHL',
	'Sanima Mai Hydropower Ltd.': 'SHPC',
	'Sagarmatha Insurance Co. Ltd.': 'SIC',
	'Shikhar Insurance Co. Ltd.': 'SICL',
	'Shree Investment Finance Co. Ltd.': 'SIFC',
	'Siddhartha Investment Growth Scheme - 2': 'SIGS2',
	'Siddhartha Insurance Ltd.': 'SIL',
	'Sindhu Bikash Bank Ltd': 'SINDU',
	'SANJEN JALAVIDHYUT COMPANY LIMITED': 'SJCL',
	'Samudayik Laghubitta Bittiya Sanstha Limited': 'SLBSL',
	'Sanima Large Cap Fund': 'SLCF',
	'Sanima Life Insurance Limited': 'SLI',
	'Surya Life Insurance Company Limited': 'SLICL',
	'Samata Gharelu Laghubitta Bittiya Sanstha Limited': 'SMATA',
	'Support Microfinance Bittiya Sanstha Ltd.': 'SMB',
	'Swabhimaan Laghubitta Bittiya Sanstha Limited': 'SMFBS',
	'Summit Laghubitta Bittiya Sanstha Limited': 'SMFDB',
	'Sparsha Laghubitta Bittiya Sanstha Limited': 'SPARS',
	'Samling Power Company Limited': 'SPC',
	'Synergy Power Development Ltd.': 'SPDL',
	'Sunrise Bank Limited': 'SRBL',
	'10.25% Sunrise Bank Debenture 2083': 'SRBLD83',
	'10% Sunrise Debenture 2080': 'SRD80',
	'Shree Ram Sugar Mills Limited': 'SRS',
	'Shiva Shree Hydropower Ltd': 'SSHL',
	'Salt Trading Corporation': 'STC',
	'Tinau Mission Development Bank Limited': 'TMDBL',
	'Terhathum Power Company Limited': 'TPC',
	'Taragaon Regency Hotel Limited': 'TRH',
	'United Finance Ltd.': 'UFL',
	'United Insurance Co. (Nepal) Ltd.': 'UIC',
	'Upakar Laghubitta Bittiya Sanstha Limited': 'ULBSL',
	'Union Life Insurance Company Limited': 'ULI',
	'United Modi Hydropower Ltd.': 'UMHL',
	'United IDI Mardi RB Hydropower Limited.': 'UMRH',
	'Union Hydropower Limited': 'UNHPL',
	'Unilever Nepal Limited': 'UNL',
	'UNIVERSAL POWER COMPANY LTD': 'UPCL',
	'Upper Tamakoshi Hydropower Ltd': 'UPPER',
	'Unnati Sahakarya Laghubitta Bittiya Sanstha Limited': 'USLB',
	'12% ICFC Finance Limited Debenture 2083': 'ICFC',
	'Best Finance Company Ltd.': 'BFC',
	'Bishal Bazar Company Limited': 'BBCL',
	'Chandragiri Hills Limited':'CGH',
	'Chilime Hydropower Company Limited': 'CHCL'
}